// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2afEckf4VJzPrc_K1mng-2itbqcP6C3E',
    appId: '1:1034084671943:web:1fa224dbf0bb7ca62cf9e2',
    messagingSenderId: '1034084671943',
    projectId: 'customer-app-47b79',
    authDomain: 'customer-app-47b79.firebaseapp.com',
    storageBucket: 'customer-app-47b79.appspot.com',
    measurementId: 'G-81RJPV6B3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09FezC5fJFfhX82hizUBmrpmwlOd0QP8',
    appId: '1:1034084671943:android:2cab639b2a1dea442cf9e2',
    messagingSenderId: '1034084671943',
    projectId: 'customer-app-47b79',
    storageBucket: 'customer-app-47b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBokwSNZMhouJTSYLgGFcjoMvf29ZnCKkw',
    appId: '1:1034084671943:ios:67bf0e0b233ee28a2cf9e2',
    messagingSenderId: '1034084671943',
    projectId: 'customer-app-47b79',
    storageBucket: 'customer-app-47b79.appspot.com',
    iosBundleId: 'com.purplestage.clientapp',
  );
}
